# Copyright (C) 2017 ETH Zurich, University of Bologna and GreenWaves Technologies
# All rights reserved.
#
# This software may be modified and distributed under the terms
# of the BSD license.  See the LICENSE file for details.

PULP_APP = helloworld
PULP_APP_FC_SRCS = helloworld.c
PULP_CFLAGS = -O3 -g #-DPRINTF_UART

#PLPBRIDGE_FLAGS += -f -hyper
include ~/workspace_pulp/hero/pulp/sdk/tools/pulp-rules/rules/pulp_rt.mk


